[package]
name = "openaip"
description = "OpenAIP file parser for Rust"
version = "0.1.0"
authors = ["Tobias Bieniek <tobias.bieniek@gmail.com>"]
repository = "https://github.com/Turbo87/openaip-rs"
documentation = "https://docs.rs/openaip"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "Turbo87/openaip-rs", branch = "master" }

[dependencies]
xmltree = "0.4.0"

[dev-dependencies]
approx = "0.2.0"
